config/routes.rb
Rails.application.routes.draw do
  get 'report/index'

  resources :bills, only: [:index, :new, :create, :show]
  root "bills#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bill.rb
class Bill < ApplicationRecord

  attr_accessor :event_attendes, :bill_contributors, :contributions

  has_many :user_bills
  has_many :users, :through => :user_bills
  has_many :bill_payments

  validates :event,
            presence: true
  validates :event,
            inclusion: { in: %w(lunch dinner snacks),
            message: "%{value} is not a valid event" },
            if: :event
  validates :entry_date,
            presence: true
  validates :location,
            presence: true
  validates :amount,
            presence: true
  validates :amount,
            numericality: { only_integer: true },
            if: :amount
  validates :event_attendes, :bill_contributors, :contributions,
            presence: true

  validate :cross_verify_contributors, if: Proc.new { event_attendes.present? && bill_contributors.present? }
  validate :verify_contributions, if: Proc.new { contributions.present? && bill_contributors.present? }

  EVENTS = [["Lunch", "lunch"], ["Dinner", "dinner"], ["Snacks", "snacks"]]

  def contributions=(value)
    @contributions = value.delete_if {|number| number.to_i.eql?(0)}
  end

  private

  def cross_verify_contributors
    errors.add(:bill_contributors, "Bill contributors should be included in event attendes") unless (event_attendes & bill_contributors).sort == bill_contributors.sort
  end

  def verify_contributions
    errors.add(:contributions, "Bill contributors and no of amount mismatch or invalid") if contributions.length != bill_contributors.length
    errors.add(:contributions, "Contributions and total amount is mismatch") if contributions.map(&:to_i).reduce(0, :+) != amount.to_i
  end

end

app/models/bill_payment.rb
class BillPayment < ApplicationRecord
  belongs_to :bill
  belongs_to :user

  def self.user_bill_payments
    select("bill_payments.user_id,
            users.name as user_name,
            bills.event,
            bills.amount as bill_amount,
            bill_payments.amount as paid_amount,
            bills.id as bill_id,
            count(DISTINCT user_bills.user_id) as user_count
          ").joins("LEFT JOIN bills
                    ON bills.id = bill_payments.bill_id
                    LEFT JOIN user_bills
                    ON user_bills.bill_id = bill_payments.bill_id
                    LEFT JOIN users
                    ON users.id = bill_payments.user_id
                  ").group("bill_payments.id,
                            users.name,
                            bills.event,
                            bills.amount,
                            bill_payments.amount,
                            bills.id
                          ").order("bill_payments.user_id")
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_bills
  has_many :bills, :through => :user_bills
  has_many :bill_payments
  has_many :user_payments
end

app/models/user_bill.rb
class UserBill < ApplicationRecord
  belongs_to :user
  belongs_to :bill
end

app/models/user_payment.rb
class UserPayment < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show]
  before_action :fetch_users, only: [:new, :create]

  # GET /bills
  # GET /bills.json
  def index
    @bills = Bill.all
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
    @attendies = @bill.users
    @bill_payments = @bill.bill_payments.includes(:user)
  end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(bill_params)

    respond_to do |format|
      begin
        ActiveRecord::Base.transaction do
          if @bill.save
            @bill.event_attendes.each do |user_id|
              ub = UserBill.new({bill_id: @bill.id, user_id: user_id})
              ub.save
            end
            @bill.bill_contributors.each_with_index do |contributor_id, index|
              bp = BillPayment.new({bill_id: @bill.id, user_id: contributor_id, amount: @bill.contributions[index]})
              bp.save
            end
            (@bill.event_attendes - @bill.bill_contributors).each do |non_contributor|
              bp = BillPayment.new({bill_id: @bill.id, user_id: non_contributor, amount: 0})
              bp.save
            end
            format.html { redirect_to @bill, notice: 'Bill was successfully created.' }
            format.json { render :show, status: :created, location: @bill }
          else
            format.html { render :new }
            format.json { render json: @bill.errors, status: :unprocessable_entity }
          end
        end
      rescue Exception => e
        Rails.logger.info e.message
        flash[:notice] = "Something went wrong, please try again"
        format.html {redirect_to bills_path}
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit( :event, :entry_date, :location, :amount,
                                    :event_attendes => [], :bill_contributors => [],
                                    :contributions => []
                                  )
    end

    def fetch_users
      @users = User.all
    end
end

app/controllers/report_controller.rb
class ReportController < ApplicationController
  def index
    @bills = Bill.all
    @bill_payments = BillPayment.user_bill_payments
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def settlement_info(bill_payments)
    h = Hash.new
    bill_payments.each do |bill_payment|
      h[bill_payment.user_id.to_s] = Hash.new unless h[bill_payment.user_id.to_s].present?
      h[bill_payment.user_id.to_s]["user_name"] = bill_payment.user_name

      h[bill_payment.user_id.to_s]["paid_amount"] = 0 unless h[bill_payment.user_id.to_s]["paid_amount"].present?
      h[bill_payment.user_id.to_s]["paid_amount"] += bill_payment.paid_amount

      h[bill_payment.user_id.to_s]["bill_amount"] = 0 unless h[bill_payment.user_id.to_s]["bill_amount"].present?
      h[bill_payment.user_id.to_s]["bill_amount"] += (bill_payment.bill_amount/bill_payment.user_count)
    end

    h.each do |key, value|
      h[key]["settle_amount"] = h[key]["paid_amount"] - h[key]["bill_amount"]
    end

    return h
  end

end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/views/bills/_form.html.erb
<%= form_for(bill) do |f| %>
  <% if bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% bill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event %>
    <%= f.select("event", options_for_select(Bill::EVENTS, (params[:bill].present? ? params[:bill][:event] : Bill::EVENTS.first[0].to_s))) %>
  </div>

  <div class="field">
    <%= f.label :entry_date %>
    <%= f.datetime_select :entry_date %>
  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>

  <div class="field">
    <%= f.label :amount %>
    <%= f.number_field :amount %>
  </div>

  <div class="field">
    <label>Event Attendes</label>
    <% @users.each do |user| %>
      <%= f.check_box("event_attendes", {multiple: true, checked: (params[:bill].present? && params[:bill][:event_attendes].present? && params[:bill][:event_attendes].include?(user.id.to_s))}, user.id, nil) %> <%= user.name %>
    <% end %>
  </div>

  <div class="field">
    <label>Bill Contributors</label>
    <% @users.each_with_index do |user, index| %>
      <%= f.check_box( "bill_contributors", {multiple: true, checked: (params[:bill].present? && params[:bill][:bill_contributors].present? && params[:bill][:bill_contributors].include?(user.id.to_s)), class: "bill_contributors"}, user.id, nil) %> <%= user.name %>
      <br/>
      Amount: <%= f.text_field("contributions", {id: "contributions_#{user.id}", multiple: true, value: (params[:bill].present? ? params[:bill][:contributions][index] : "")}) %> $
      <br/><br/>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bills/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bills</h1>

<table>
  <thead>
    <tr>
      <th>Event</th>
      <th>Entry date</th>
      <th>Location</th>
      <th>Amount</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bills.each do |bill| %>
      <tr>
        <td><%= bill.event %></td>
        <td><%= bill.entry_date %></td>
        <td><%= bill.location %></td>
        <td><%= bill.amount %></td>
        <td><%= link_to 'Show', bill %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bill', new_bill_path %> || <%= link_to "Reports", report_index_path %>

app/views/bills/new.html.erb
<h1>New Bill</h1>

<%= render 'form', bill: @bill %>

<%= link_to 'Back', bills_path %>

app/views/bills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event:</strong>
  <%= @bill.event %>
</p>

<p>
  <strong>Entry date:</strong>
  <%= @bill.entry_date %>
</p>

<p>
  <strong>Location:</strong>
  <%= @bill.location %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @bill.amount %>
</p>


<p>
  <strong>Attendies:</strong>
  <br/>
  <% @attendies.each do |attendy| %>
    -> <%= attendy.name %> <br/>
  <% end %>
</p>

<p>
  <strong>Bill Payments:</strong>
  <table border="1" style="margin-left: 32px;">
    <thead>
      <th>Contributor</th>
      <th>Amount</th>
    </thead>
    <tbody>
      <% @bill_payments.each do |bill_payment| %>
        <tr>
          <td><%= bill_payment.user.name %></td>
          <td><%= bill_payment.amount %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</p>
<%= link_to 'Back', bills_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wallet</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/report/index.html.erb
<h1>Report#index</h1>
<label>Bills:</label> <br/>
<table border="1">
  <thead>
    <th>Event</th>
    <th>Date</th>
    <th>Amount</th>
  </thead>
  <tbody>
    <% total_amount = 0 %>
    <% @bills.each do |bill| %>
      <tr>
        <td><%= bill.event %></td>
        <td><%= bill.entry_date %></td>
        <td><%= bill.amount %></td>
      </tr>
      <% total_amount += bill.amount %>
    <% end %>
    <tr>
      <td colspan="2" style="text-align: center; font-weight: bold;">Total</td>
      <td><%= total_amount %></td>
    </tr>
  </tbody>
</table>
<br><br>
================================================================================

<label>User Payments:</label> <br/>
<table border="1">
    <thead>
      <th>Contributor</th>
      <th>Paid</th>
      <th>Bill amount</th>
      <th>Event</th>
      <th>No of contributors</th>
      <th>Difference</th>
    </thead>
    <tbody>
      <% @bill_payments.each do |bill_payment| %>
        <tr>
          <td><%= bill_payment.user_name %></td>
          <td><%= bill_payment.paid_amount %></td>
          <td><%= bill_payment.bill_amount %></td>
          <td><%= bill_payment.event %></td>
          <td><%= bill_payment.user_count %></td>
          <td><%= (bill_payment.paid_amount - (bill_payment.bill_amount/bill_payment.user_count)) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br><br>
=================================================================================


<label>Payment Settlements:</label> <br/>
<table border="1">
  <thead>
    <th>Name</th>
    <th>Paid</th>
    <th>Bill amount</th>
    <th>Settlement Amount</th>
  </thead>
  <tbody>
    <% settlement_info(@bill_payments).each do |key, settlement| %>
      <tr>
        <td><%= settlement["user_name"] %></td>
        <td><%= settlement["paid_amount"] %></td>
        <td><%= settlement["bill_amount"] %></td>
        <td><%= settlement["settle_amount"] %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<h4>Note: -ve amount has to be paid by user</h4>


<br/><br/>
<%= link_to 'Back', bills_path %>